source 'https://cdn.cocoapods.org/'
use_frameworks!

target 'BufferSlider_Example' do
  pod 'BufferSlider', :path => '../'
end

target 'BufferSlider_Tests' do
  pod 'BufferSlider', :path => '../'
end



